# Generated by Django 3.2.5 on 2023-11-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='ownerID',
        ),
    ]
