# Generated by Django 3.2.5 on 2023-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='ownerID',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
