# Generated by Django 3.2.5 on 2023-11-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatroom_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='lastUpdate',
            field=models.TimeField(auto_now=True),
        ),
    ]
