# Generated by Django 3.2.5 on 2023-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_ide_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide',
            name='code',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
