# Generated by Django 3.2.5 on 2023-11-27 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_ide_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide',
            name='chat_room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom', verbose_name='chat_room'),
        ),
    ]
