# Generated by Django 3.2.5 on 2023-12-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_ide_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='media/images/basicProfile.png', upload_to='images/'),
        ),
    ]
